# The course so far...

* Whirlwind through Python
* Filer, CLI, OO
* Plotting
* Numpy
* Pandas
* Multiprocessing, generators and requests
* Graphs and PageRank
* Webscraping

## What is left ...

* Feature engineering
* Neural networks
* Image processing
* Movement detection
* Project work

# Learning objectives

## Skills 

* Write Python scripts and programs using common language constructs in the read-eval-print-loop (REPL), “Jupyter Notebooks”, as well as separate self-contained programs. 

* Download files from the web programmatically, as well as reading most common file formats programmatically. 

* Create various types of plots programmatically to share insight into data. 

* Apply Python’s scientific libraries and some of the most prominent algorithms in data science for problem solving and complexity reduction. 

* Programmatically, process images and streams of images. 

* Automate repetitive and boring tasks for example for data collection or UI testing. 

 



## Competencies 

* collect various types of data 

* formulate problems about this data 

* implement solutions to given problem statements 

* present results on an abstract as well as technical level 

*  gain experiences in code reviews by reviewing Python code of their fellow students

## Agenda

* Linear algebra
  * Vector and matrix operations
  * Matrix operations
* Feature engineering 
* Machine learning basics

## Linear algebra
##### Linear algebra is the branch of mathematics that deals with vector spaces.
Source: Data Science From Scratch, chapter 4.

##### 4 important concepts we will work with are:
1. **vectors** (list of numbers)
2. **matrices** (matrix in plural) 2 dimensional list of numbers (list of vectors) or (one-hot-encoded relationships between x and y axis)
3. **vector space** (the n-dimensional coordinate system in which the vectors can move around)
4. **vector arithmetics** (addition, substraction, division and multiplication of vectors with vectors and vectors with scalars)
5. **dot products** sum of products of all elements of 2 vectors resulting in single value
6. **matrix products** 2 matrices joined to one where each row element from one matrix multiplied by each column element in another matrix summed up in each cell of the resulting matrix


## Vector operations

Vectors are list of numbers, and you can do a number of things with them!
For more background understanding see this (almost 4 hour) course:  
https://www.youtube.com/watch?v=T3TpdPmTLso


In [1]:
import numpy as np

In [1]:
scalar = 7

v = np.array([1, 5, 8, -2, 6])

In [2]:
v.shape

(5,)

In [4]:
np.array([[1], [5], [8], [-2], [0]]).shape

(5, 1)

In [5]:
np.array([[1, 3], [0]]).shape

(2,)

In [5]:
v.reshape(-1, 1) == v.reshape(5,1)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

### Vector - scalar operations

In [3]:
# Addition
v + scalar

array([ 8, 12, 15,  5, 13])

In [9]:
# Subtraction
v - scalar

array([-6, -2,  1, -9, -1])

In [10]:
# Division
v / scalar

array([ 0.14285714,  0.71428571,  1.14285714, -0.28571429,  0.85714286])

In [11]:
# Multiplication
v * scalar

array([  7,  35,  56, -14,  42])

### Vector - vector operations

In [6]:
v = np.array([1, 5, 8, -2, 6])
p = np.array([2, 0, -1])

In [7]:
v + v

array([ 2, 10, 16, -4, 12])

![](images/vector_addition.svg)

In [8]:
# ValueError vectors of different dimensions can not be added together
v + p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [15]:
v - v

array([0, 0, 0, 0, 0])

In [17]:
v / v

array([1., 1., 1., 1., 1.])

In [19]:
v * p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Matrix 
A matrix is a 2 dimensional data structure like a list a of lists b where b are all of same length   
One Matrix, Two Matrices

##  Matrix operations:

Math: $v = \begin{bmatrix} -2 & 0 & 1 \\ 5 & -4 & 2 \\ 7 & -1 & 3\end{bmatrix}$

Python:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
```

In [11]:
import numpy as np
scalar = 7
v = np.array([2, 0, -1])

m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
print('type of v',type(v),'\ntype of m:',type(m))

type of v <class 'numpy.ndarray'> 
type of m: <class 'numpy.ndarray'>


In [9]:
m.shape

(3, 3)

### Matrix - scalar operations

In [23]:
m + scalar # Addition

array([[ 5,  7,  8],
       [12,  3,  9],
       [14,  6, 10]])

In [24]:
m - scalar # Subtraction

array([[ -9,  -7,  -6],
       [ -2, -11,  -5],
       [  0,  -8,  -4]])

In [25]:
m / scalar # Division

array([[-0.28571429,  0.        ,  0.14285714],
       [ 0.71428571, -0.57142857,  0.28571429],
       [ 1.        , -0.14285714,  0.42857143]])

In [26]:
m * scalar # Multiplication

array([[-14,   0,   7],
       [ 35, -28,  14],
       [ 49,  -7,  21]])

### Matrix - vector operations

In [10]:
print("Matrix: \n", m)
print("\nVector: ", v)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]

Vector:  [ 2  0 -1]


In [11]:
m + v

array([[ 0,  0,  0],
       [ 7, -4,  1],
       [ 9, -1,  2]])

In [12]:
m - v

array([[-4,  0,  2],
       [ 3, -4,  3],
       [ 5, -1,  4]])

In [13]:
print("Matrix: \n", m)
print("Vector: ", p)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  0 -1]


In [14]:
m / p

/home/tha/.anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/tha/.anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[-1. ,  nan, -1. ],
       [ 2.5, -inf, -2. ],
       [ 3.5, -inf, -3. ]])

In [12]:
m * p # Note, this is NOT called matrix multiplication!!! Matrix multiplication is using the dot product see here: https://www.mathsisfun.com/algebra/matrix-multiplying.html

array([[-4,  0, -1],
       [10,  0, -2],
       [14,  0, -3]])

In [15]:
print("Matrix: \n", m)
print("Vector: ", v)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  0 -1]


### Matrix - matrix operations

In [17]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])

In [18]:
m.shape

(3, 3)

In [19]:
m + m

array([[-4,  0,  2],
       [10, -8,  4],
       [14, -2,  6]])

In [20]:
m - m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
m / m

/home/tha/.anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., nan,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
m * m # Note, this is NOT matrix multiplication

array([[ 4,  0,  1],
       [25, 16,  4],
       [49,  1,  9]])

### Entry-wise product, Hadamard product
Is not a matrix product (see further down)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hadamard_product_qtl1.svg/220px-Hadamard_product_qtl1.svg.png)

In [23]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])
print('m:\n',m,'\nq:\n',q)

m:
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]] 
q:
 [[ 0  7]
 [-3  2]
 [ 1  5]]


In [24]:
q[0]

array([0, 7])

In [46]:
q.shape

(3, 2)

In [25]:
m + q

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [26]:
m * q

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [27]:
np.matmul(m, q)

array([[ 1, -9],
       [14, 37],
       [ 6, 62]])

### Matrix multiplication

![](images/matmul.png)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/313px-Matrix_multiplication_diagram_2.svg.png)

## Exercise Matrix multiplication

Multiply the following matrix `m × q` by hand:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])
```

In [61]:
m.dot(q).shape

(3, 2)

In [67]:
q.T.shape

(2, 3)

## Matrix transpose

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Matrix_transpose.gif/200px-Matrix_transpose.gif)

In [80]:
a = np.array([[-2, 5], [0, 4]])
b = np.array([0, 7])

35

In [ ]:
np.arange(12).reshape(3, 4).T

In [81]:
m.T

array([[-2,  5,  7],
       [ 0, -4, -1],
       [ 1,  2,  3]])

In [82]:
q = np.array([[0, 7], [-3, 2], [1, 5]])

In [84]:
q.shape

(3, 2)

In [85]:
q.T.shape

(2, 3)

## Real life example using the matrix multiplication
Building on this source: https://www.mff.cuni.cz/veda/konference/wds/proc/pdf06/WDS06_106_m8_Ulrychova.pdf

Three persons p1,p2,p3 wants to buy some apples, bananas, clementines and eggplants. Each person wants to buy differing amounts and can buy them in two different shops S1, S2.
Which shop is the best for each person p1, p2, p3 to pay as little as possible?  
The individual prices and desired quantities of the commodities are given in the following tables:

**Needed fruits and veggies**  

|person|apple|banana|clementine|eggplant|
|--|--|--|--|--|
|p1|6|5|3|1|
|p2|3|6|2|2|
|p3|3|4|3|1|

**Prices in the 2 shops**  

|merchandise|S1| S2|
|--|--|--|
|apples|1.50| 1.00|
|bananas |2.00| 2.50|
|clementines |5.00 |4.50|
|eggplants |16.00 |17.00|

For example, the amount spent by the **person p1** would be:  
**Shop s1**: `6 · 1.50 + 5 · 2.00 + 3 · 5.00 + 1 · 16.00 = 50`  
**Shop s2**: `6 · 1.00 + 5 · 2.50 + 3 · 4.50 + 1 · 17.00 = 49`

**The 2 metrices would look like this:**

```
P = [[6,5,3,1],
     [3,6,2,2],
     [3,4,3,1]]
``` 
and  
```
Q = [[1.50,  1.00],
     [2.00,  2.50],
     [5.00,  4.50],
     [16.00, 17.00]]
``` 
The matrix product looks like this
```
R = PQ = [[50.00, 49.00],
          [58,50, 61.00],
          [43.50, 43.50]]
```
|persons|shop 1 sum of prod|shop 2 sum of prod|
|--|--|--|
|p1|50.00|49.00|
|p2|58.50|61.00|
|p3|43.50|43.50|

##### Conclusion:
person 1 should go to shop 2  
person 2 should go to shop 1 and  
person 3 can go to either shop  


In [6]:
# Above calculation done with numpy:

import numpy as np
P = np.array([[6,5,3,1],
     [3,6,2,2],
     [3,4,3,1]])
Q = np.array([[1.50,  1.00],
     [2.00,  2.50],
     [5.00,  4.50],
     [16.00, 17.00]])
R = P.dot(Q)
R 

array([[50. , 49. ],
       [58.5, 61. ],
       [43.5, 43.5]])

## Class exercise
Given the below dictionarys find out where each of the 4 people find the cheapest shopping according to their needs.
```python
shoppers = {
'Paula':{'Is':4,'Juice':2,'Kakao':3,'Lagkager':2},
'Peter':{'Is':2,'Juice':5,'Kakao':0, 'Lagkager':4},
'Pandora':{'Is':5,'Juice':3, 'Kakao':4, 'Lagkager':5},
'Pietro':{'Is':1,'Juice':8, 'Kakao':9, 'Lagkager':1}
}
shop_prices = {
    'Netto': {'Is':10.50,'Juice':2.25,'Kakao':4.50,'Lagkager':33.50},
    'Fakta': {'Is':4.00,'Juice':4.50,'Kakao':6.25,'Lagkager':20.00}
}
```
Hint: you can use pandas and Transpose to create dataframe: `pd.DataFrame(shoppers).T`


Netto   Fakta
Paula    127.00   83.75
Peter    166.25  110.50
Pandora  244.75  158.50
Pietro   102.50  116.25